import type { Trade } from './types';

export const sampleTrades: Trade[] = [
  {
    id: '1',
    timestamp: '2026-06-27T09:31:00Z',
    symbol: 'AAPL',
    side: 'BUY',
    quantity: 500,
    price: 213.45,
    assetClass: 'Equity',
    account: 'ACC-1001',
    advisor: 'J. Smith',
    status: 'Executed',
    notes: 'Core position add',
  },
  {
    id: '2',
    timestamp: '2026-06-27T09:45:00Z',
    symbol: 'TLT',
    side: 'BUY',
    quantity: 1000,
    price: 98.20,
    assetClass: 'ETF',
    account: 'ACC-1002',
    advisor: 'J. Smith',
    status: 'Executed',
    notes: 'Duration hedge',
  },
  {
    id: '3',
    timestamp: '2026-06-27T10:02:00Z',
    symbol: 'MSFT',
    side: 'SELL',
    quantity: 200,
    price: 441.80,
    assetClass: 'Equity',
    account: 'ACC-1001',
    advisor: 'A. Jones',
    status: 'Executed',
    notes: 'Rebalance trim',
  },
  {
    id: '4',
    timestamp: '2026-06-27T10:15:00Z',
    symbol: 'BND',
    side: 'BUY',
    quantity: 300,
    price: 72.55,
    assetClass: 'ETF',
    account: 'ACC-1003',
    advisor: 'A. Jones',
    status: 'Pending',
    notes: '',
  },
  {
    id: '5',
    timestamp: '2026-06-27T10:30:00Z',
    symbol: 'GOOGL',
    side: 'BUY',
    quantity: 50,
    price: 178.90,
    assetClass: 'Equity',
    account: 'ACC-1002',
    advisor: 'J. Smith',
    status: 'Failed',
    notes: 'Order rejected - insufficient funds',
  },
];
